SELECT T.FLAVOR FROM
(SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) + SUM(F.TOTAL_ORDER) TOTAL_ORDER
FROM JULY J JOIN FIRST_HALF F ON J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY TOTAL_ORDER DESC) T
WHERE ROWNUM BETWEEN 1 AND 3;